[package]
name = "rain-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true, optional = true }
tracing-appender = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

gtk = { workspace = true, optional = true }
gtk4-layer-shell = { workspace = true, optional = true }

kanal = { workspace = true, optional = true }

tokio = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
divan = { workspace = true }

[[bench]]
name = "fuzzy_bench"
harness = false
required-features = ["finder"]

[features]
default = ["log"]

finder = ["dep:kanal"]
gtk = ["dep:gtk", "dep:gtk4-layer-shell"]
log = ["dep:tracing", "dep:tracing-appender", "dep:tracing-subscriber"]
tokio = ["dep:tokio"]

full = ["log", "finder", "gtk", "tokio"]
